# Generated by Django 5.0.6 on 2024-06-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ppm_products", "0004_alter_product_image_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
